name: Crear Imagen Docker y Desplegar

on:
  push:
    branches: [ "docker-image" ]
  pull_request:
    branches: [ "docker-image" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5.0.0

    # https://github.com/marketplace/actions/docker-metadata-action
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5.8.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw, value=${{ env.IMAGE_TAG }}

    # https://github.com/marketplace/actions/docker-login
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3.6.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        push: True
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy-in-kubernetes-cluster:
    needs: [ build-and-push-image ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5.0.0

    # https://github.com/marketplace/actions/kubectl-tool-installer
    - name: Install Kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: kubectl apply -f kube-deployment.yaml
