name: Crear Imagen Docker y Desplegar

on:
  push:
    branches: [ "docker-image" ]
  pull_request:
    branches: [ "docker-image" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    # https://github.com/marketplace/actions/docker-metadata-action
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw, value=latest

    # https://github.com/marketplace/actions/docker-login
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: True
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy-in-kubernetes-cluster:
    needs: [ build-and-push-image ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    # https://github.com/marketplace/actions/kubectl-tool-installer
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4
      with:
        version: latest

    # https://github.com/marketplace/actions/kubectl-simple
    - name: kubectl-simple
      uses: steebchen/kubectl@v2
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f kube-deployment.yaml
